version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: liquidazione_postgres
    environment:
      POSTGRES_DB: liquidazione_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 