api:
  # Configurazioni generali dell'API
  title: "Liquidazione IA API"
  version: "1.0.0"
  description: "API per la gestione di documenti di liquidazione giudiziale"
  prefix: "/api/v1"

  # Configurazioni del server
  server:
    host: "0.0.0.0"
    port: 8000
    workers: 4
    debug: false
    reload: false
    timeout_keep_alive: 5

  # Configurazioni CORS
  cors:
    enabled: true
    allow_origins:
      - "http://localhost:3000"
    allow_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allow_headers:
      - "*"
    allow_credentials: true
    max_age: 600

  # Configurazioni rate limiting
  rate_limit:
    enabled: true
    max_requests: 100
    time_window_seconds: 60
    by_ip: true
    exclude_paths:
      - "/api/v1/health"
      - "/api/v1/docs"

  # Configurazioni documentazione
  docs:
    enabled: true
    path: "/docs"
    redoc_path: "/redoc"
    openapi_path: "/openapi.json"
    swagger_ui_parameters:
      docExpansion: "none"
      defaultModelsExpandDepth: 1

  # Configurazioni middleware
  middleware:
    compression:
      enabled: true
      minimum_size: 500
      level: 9
    trusted_hosts:
      enabled: true
      allowed_hosts:
        - "localhost"
        - "127.0.0.1"
    http_basic:
      enabled: false
      username: "admin"
      password: "password"

  # Configurazioni logging
  logging:
    enabled: true
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    access_log: true
    error_log: true
    log_file: "logs/api.log"

  # Configurazioni sicurezza
  security:
    ssl_enabled: false
    ssl_keyfile: ""
    ssl_certfile: ""
    proxy_headers: true
    max_upload_size_mb: 50
    allowed_upload_extensions:
      - ".pdf"
      - ".doc"
      - ".docx"
      - ".txt"
      - ".jpg"
      - ".png" 